name = "R&R"
author = "Electrolyte"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af6d916849701736d6964c6717e4b39d9ec17b877bf5c993c923e8e5f803cdc5"

[versions]
fabric = "0.16.5"
minecraft = "1.21"
