name = "R&R"
author = "Electrolyte"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05ff9f3b0bc4697a98e9e68bc1d62f540b6b9f5949cb9a532db1a11e87f916fc"

[versions]
fabric = "0.16.5"
minecraft = "1.21"
