name = "R&R"
author = "Electrolyte"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37a92ac86aa405af4eafdbb92c654977de2a0f4c4e92b366484b14bb778957b2"

[versions]
fabric = "0.16.5"
minecraft = "1.21"
