name = "R&R"
author = "Electrolyte"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "610d9cfa68c5718c399a7c30fc579d40e65cfe303d44398c1a62369e7e62c502"

[versions]
fabric = "0.16.5"
minecraft = "1.21"
